Refactor sdk
invariant-labs/protocol-a0 pull request #163
Opened 2024-01-10 12:06 UTC by zielvna

2024-01-10 14:16 UTC, Sniezka1927 requested changes

2024-01-10 14:39 UTC, Sniezka1927 commented on sdk/math/storage/fee_tier.rs
> +    let tick_spacing: u64 = convert!(js_tick_spacing)?;
Do not change type in struct, just in casting
```
    let tick_spacing: u64 = convert!(js_tick_spacing)?;
    resolve!(FeeTier::new(fee, tick_spacing as u16))
```

2024-01-10 15:57 UTC, Sniezka1927 approved these changes

2024-01-12 14:46 UTC, wojciech-cichocki approved these changes

2024-01-12 14:46 UTC, wojciech-cichocki commented on sdk/tests/position.test.ts
> +      assert.deepEqual(result.events[0].address, account.address.toString())
Adding the util function for comparing events would be helpful here. it make tests code more readable and , we will likely need to compare events when testing stats or event subscription

2024-01-12 15:36 UTC, wojciech-cichocki approved these changes

2024-01-12 15:45 UTC, merged