update ink and arithmetic operations
invariant-labs/protocol-a0 pull request #215
Opened 2024-03-21 14:52 UTC by zielvna

ink 5 changes:
- scale and scale info dependencies are now shipped with ink (remove them from dependencies and update imports)
- events update (update event structs and put them in separate file)
- no unchecked arithmetic (use checked arithmetic, improve error handling)
- e2e tests api changes (update all e2e tests with new api)

additional changes:
- update main contract, token contract, sdk dependencies to handle ink 5
- put swap structs in separate file
- put error enum in separate file
- update event listeners in sdk

2024-03-27 09:55 UTC, Sniezka1927 requested changes

2024-03-27 09:55 UTC, Sniezka1927 commented on src/contracts/collections/pool_keys.rs
> +                self.pool_keys_length = self.pool_keys_length.checked_sub(1).unwrap();
The possible error of checked operation should be checked. In all of the places I would add additional errors
```
InvariantError::AddOverflow
InvariantError::SubUnderflow
InvariantError::MulOverflow
InvariantError::DivOverflow
```

2024-03-27 09:55 UTC, Sniezka1927 commented on src/lib.rs
> +                        .map_err(|_| InvariantError::InvalidArithmeticOperation)?;
It would be better to specify what operation failed

2024-03-27 09:55 UTC, Sniezka1927 commented on src/contracts/structs.rs
> +pub struct CalculateSwapResult {
I think the file name could be renamed. It only contains structs related to swap.

2024-03-27 09:55 UTC, Sniezka1927 commented on src/math/types/sqrt_price.rs
> +        sqrt_price = sqrt_price.big_mul(FixedPoint::new(1000049998750));
Are you sure we need to use `big_mul`?

2024-05-06 06:47 UTC, wojciech-cichocki requested changes
There is conflicts

2024-05-06 06:47 UTC, wojciech-cichocki commented on src/contracts/collections/positions.rs
> +                .ok_or(InvariantError::SubUnderflow)?
Consider whether publicly throwing internal errors is correct?"

2024-05-06 15:50 UTC, zielvna commented on sdk/tests/invariant.test.ts
> -  it('attempt to try create pool with wrong tick sqrtPrice relationship', async () => {
before we accepted index and init sqrt price as arguments, now we just accept init sqrt price so test for relationship between index and init sqrt price is redundant

2024-05-06 15:50 UTC, zielvna commented on src/contracts/storage/tickmap.rs
> +        (tick.checked_rem(tick_spacing as i32).unwrap()),
Exactly the same, negative numbers works too

2024-05-06 18:24 UTC, zielvna commented on src/contracts/storage/tick.rs
> +            let _ = tick.update_liquidity_change(liquidity_delta, add);
clippy requires you to acknowledge that you know that function returns something and you purposefully don't want it by adding `let _ =`, that's why it's like this in tests, but I fixed that in our actual code

2024-05-15 07:49 UTC, none00y approved these changes

2024-05-22 10:49 UTC, wojciech-cichocki requested changes

2024-05-22 10:49 UTC, wojciech-cichocki commented on src/contracts/storage/tick.rs
> +            let _ = tick.update_liquidity_change(liquidity_delta, add);
IMO, there should be `unwrap()` in these tests or `unwrap_err()` if the test is intended to throw an error, instead of skipping this result

2024-05-24 06:28 UTC, wojciech-cichocki reviewed
After these changes, it is worth ensuring that no changes are required in wasm. wasm should be one-to-one with what is in the contract to avoid inconsistencies

2024-05-27 02:07 UTC, wojciech-cichocki approved these changes

2024-06-27 08:38 UTC, wojciech-cichocki approved these changes

2024-06-27 08:39 UTC, merged