Position with associates
invariant-labs/protocol-a0 pull request #290
Opened 2024-07-31 14:24 UTC by DevRozaDev

\+ remove `PositionTick` struct & `get_position_ticks` entrypoint
\+ add `get-position-with-associates` entrypoint & to sdk

2024-07-31 16:42 UTC, zielvna requested changes

2024-07-31 16:42 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    /// - `owner_id`: An `AccountId` identifying the user who owns the position.
probably it should be just `owner` here

2024-07-31 16:42 UTC, zielvna commented on sdk/tests/get-position-with-associates.test.ts
> +        assertThrowsAsync(invariant.getPositionWithAssociates(account.address, 0n), InvariantError.PositionNotFound)
you need to await `assertThrowsAsync`, otherwise the test will not wait for result of the call and always pass

2024-08-01 13:09 UTC, Sniezka1927 approved these changes

2024-08-01 13:37 UTC, wojciech-cichocki approved these changes

2024-08-01 15:06 UTC, merged