create pool keys collection and get pools message
invariant-labs/protocol-a0 pull request #83
Opened 2023-11-28 16:31 UTC by zielvna

2023-11-28 17:18 UTC, Sniezka1927 commented on src/contracts/collections/pool_keys.rs
> +            return Err(InvariantError::FeeTierAlreadyExist);
Pool instead of FeeTier

2023-11-28 17:18 UTC, Sniezka1927 commented on src/contracts/collections/pool_keys.rs
> +            .ok_or(InvariantError::FeeTierNotFound)?;
.

2023-11-28 17:18 UTC, Sniezka1927 commented on src/lib.rs
> -        fn emit_swap_event(
Why events are removed?

2023-11-29 14:27 UTC, Sniezka1927 approved these changes

2023-11-29 15:10 UTC, wojciech-cichocki requested changes

2023-11-29 15:43 UTC, wojciech-cichocki approved these changes

2023-11-29 15:50 UTC, merged