Added entrypoint descriptions
invariant-labs/protocol-a0 pull request #86
Opened 2023-11-28 21:57 UTC by Sniezka1927

2023-11-29 07:56 UTC, wojciech-cichocki requested changes
Describe parameters. BTW entyrpoints explanation is docs can definitely be improved. Check example: https://github.com/Cardinal-Cryptography/wAZERO/blob/main/traits.rs

2023-11-29 13:51 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    /// Allows an authorized user to adjust the protocol fee.
the only user that is allowed to change protocol fee is an admin so to be more specific "authorized user" should be changed to "admin"

2023-11-29 13:55 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    /// Transfers fee receiver authorization to another user.
people reading that might think that fee receiver can also transfer their role to another user, you should be more specific

2023-11-29 14:04 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    /// - Fails if the Pool key cannot be created.
also fails if the pool with created pool key does not exist

2023-11-29 14:08 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    /// - Fails if the user attempts to create a pool for the same tokens.
should fail if pool with the same tokens and fee tier already exist (you should also refactor create pool message)

2023-11-29 14:13 UTC, zielvna commented on src/contracts/entrypoints.rs
> +    /// - Fails if the DEX has insufficient balance to perform the transfer.
also fails if position can not be found

2023-11-29 15:21 UTC, zielvna approved these changes

2023-11-30 08:20 UTC, wojciech-cichocki requested changes
"External contracts" can be added as another section (Parameters, Events, Errors). There should only be PSP22 here. However it will give a lot of information

2023-11-30 10:47 UTC, wojciech-cichocki approved these changes

2023-11-30 10:48 UTC, merged